### ISSUE TITLE
`pow()` leads to issues in SDL2 audio conversion

### ISSUE THREAD

**Issue by JayFoxRox** [thrimbor/pdclib-nxdk#25]
See https://github.com/XboxDev/nxdk-sdl/pull/20#issuecomment-581448832

Additionally, I noticed that the math functions don't have any copyright header or note where they stem from / wether they were tested; this makes it hard to analyze / report such issues.

It is worth noting that the code for different precisions is exactly the same (except for type suffix on `float` constants). I'm not sure if this is enough / correct.

I also believe we never set up or check the control words for precision (I expected this in crt0). So it might be possible to get different results on different runs, depending on how the XBE was started?

**Comment by thrimbor** [comment]
Hm, would be nice to have a condensed test case for this. When poking around it seemed like the `bessel` was called with `NaN`, but that's probably just the symptom of an earlier error.

> Additionally, I noticed that the math functions don't have any copyright header or note where they stem from / wether they were tested; this makes it hard to analyze / report such issues.

I wrote them myself, and afair I tested all of them by running them on my Linux host and sanity checking the output.

> I also believe we never set up or check the control words for precision (I expected this in crt0). So it might be possible to get different results on different runs, depending on how the XBE was started?

Yeah we should fix that.
